owner: immunityledger
repo: whatsgpt-business-status

sites:
  - name: WhatsGPT
    url: https://platform.whatsgpt.biz/api
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/immunityledger/whatsgpt-business-status/master/assets/favicon.ico

assignees:
  - mazenkhalil

status-website:
  cname: status.whatsgpt.biz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/immunityledger/whatsgpt-business-status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/immunityledger/whatsgpt-business-status/master/assets/favicon.ico
  name: WhatsGPT Business Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome to WhatsGPT Business real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
